# https://dashboard.fauna.com/db/GeonHo

# createAt is not necessary because ts is exist at fauna db

type Point {
  name: String!
  pointChanges: [PointChange!]
}

type PointChange {
  amount: Int!
  note: String
  point: Point!
}

type Query {
  allPointChanges: [PointChange!]
}
